#!/bin/bash

[ -f Config.in ] && rm Config.in
echo "#This file is autogenerated. Do not change" >> Config.in

for file in package/*
do
$(echo $VAR | tr '[a-z]' '[A-Z]')
	if [ -d $file ]; then
		echo "config BR2_PACKAGE_$(echo `basename $file` | tr '[a-z]' '[A-Z]')" >> Config.in
		echo "  def_bool y" >> Config.in
	fi
done

echo "source \"\$BR2_EXTERNAL_cambricon_buildroot_PATH/Config.in.host\"" >> Config.in
